title: Hack Beyond the Code
logo: /assets/img/logo_sticker.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
site.github.is_user_page: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
title: Hack Beyond the Code
description: AIED 2024 - Full-Day Workshop
markdown: GFM
