title: Hack for AI Literacy
logo: /assets/img/hackAILiteracy.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
title: Hack Beyond the Code
description: Building a Toolbox of Human-Centred Strategies for AI Literacy
